source/RouteOptiWeb/Controllers/NonyusakiTorikomiController.cs
using Microsoft.AspNetCore.Mvc;
using RouteOptiWeb.Common;
using RouteOptiWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RouteOptiWeb.Controllers
{
    public class NonyusakiTorikomiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Button_kata(List<IFormFile> UploadFile)
        //{
        //    var files = UploadFile;
        //    var fileList = new List<NonyusakiTorikomiModel>();
        //    var headerList = new List<List<NonyusakiTorikomiModel.Header>>();
        //    var detailrList = new List<List<NonyusakiTorikomiModel.Detail>>();

        //    // 対象のファイル形式================
        //    var file_xlsx = ".xlsx";
        //    var file_xls = ".xls";
        //    var file_xlw = ".xlw";
        //    //================================

        //    ViewData.Add("erroremess", null);
        //    ViewData.Add("successmess", null);



        //    return View();

        //}

        public IActionResult ExcelButton()
        {
            DataTable dt = GetNonyusakiData();

            //会社ID取得
            int wid = int.Parse(User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).First().Value);
            //ユーザー名取得
            string UserCode = User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).Skip(2).First().Value.ToString();

            // ファイル名
            var tmpFilename = "納入先情報取込_" + wid + "_" + UserCode + DateTime.Now.ToString("yyyyMMddHHmmss");

            // 出力フォルダパス
            var rootPath = Directory.GetCurrentDirectory();
            var folderPath = Path.Combine(rootPath, @"wwwroot\DownloadFiles\Nonyusaki");

            //Webサーバーのdownloadフォルダーがない場合は作成
            if (!System.IO.Directory.Exists(folderPath))
            {
                System.IO.Directory.CreateDirectory(folderPath);
            }

            // 出力パス
            var expPath = Path.Combine(folderPath, tmpFilename);

            //ヘッダーをListに作成
            List<string> hederList = Util.HederListCreate("Nonyusaki");

            // Excelファイル生成
            Util.ExportExcel(dt, expPath, hederList, null, "", "納入先情報取込");

            var file = System.IO.File.ReadAllBytes(expPath);
            return File(file, System.Net.Mime.MediaTypeNames.Application.Octet, "納入先情報取込.xlsx");
        }

        private DataTable GetNonyusakiData()
        {
            DataTable data;
            using (MSSQLAccess database = new MSSQLAccess())
            {
                //パラメーターをクリアー
                database.ClearParam();

                int wid = int.Parse(User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).First().Value);//会社IDの取得
                //会社IDの取得
                database.SetParam("@wid", SqlDbType.Int, wid);//パラメータセット
                //---------------------------------------------------------------------------

                string sqlstr = @$" SELECT 
                                          A.into_cd,
                                          A.into_name,
                                          B.address,
                                          A.bin_no,
                                          A.available_car,
                                          A.work_time,
                                          CASE WHEN A.time_flg = 1 THEN '有' ELSE '無' END,
                                          A.start_time,
                                          A.end_time,
                                          CASE WHEN SUBSTRING(A.week, 1, 1) = 1 THEN '〇' ELSE '' END,
                                          CASE WHEN SUBSTRING(A.week, 2, 1) = 1 THEN '〇' ELSE '' END,
                                          CASE WHEN SUBSTRING(A.week, 3, 1) = 1 THEN '〇' ELSE '' END,
                                          CASE WHEN SUBSTRING(A.week, 4, 1) = 1 THEN '〇' ELSE '' END,
                                          CASE WHEN SUBSTRING(A.week, 5, 1) = 1 THEN '〇' ELSE '' END,
                                          CASE WHEN SUBSTRING(A.week, 6, 1) = 1 THEN '〇' ELSE '' END,
                                          CASE WHEN SUBSTRING(A.week, 7, 1) = 1 THEN '〇' ELSE '' END,
                                          C.area_name,
                                          CASE WHEN A.depo_flg = 1 THEN '〇' ELSE '' END
                                     FROM 
                                          [m_into] AS A
                                          LEFT OUTER JOIN [m_address] AS B
                                          ON A.address_no = B.address_no
                                          LEFT OUTER JOIN [m_area] AS C
                                          ON A.area_no = C.area_no 
                                         ";

                data = database.SelectData(sqlstr);
            }
            return data;
        }
    }
}

source/RouteOptiWeb/Views/NonyusakiTorikomi/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model RouteOptiWeb.Models.NonyusakiTorikomiModel

@{
    ViewData["Title"] = "納入先情報取込画面";
    Layout = "_Layout";
}

<div class="row">
    <div style="width:800px">
        <div class="h4 mb-3 text-gray-800">
            @ViewData["Title"]
        </div>
        <div class="card shadow mb-4">
            <div class="card-header text-gray-800">
                納入先情報取込画面
            </div>
            <div class="card-body">
                <form asp-controller="NonyusakiTorikomi" method="post" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class=" card shadow mb-4">
                                <div class="card-header text-gray-800" style="padding-left:2rem">
                                    納入先情報　 エクスポート
                                </div>
                                <div class="card-body">
                                    <div class="form-group col-sm-12">
                                        <div class="form-inline">
                                            <button type="submit" asp-action="ExcelButton" id="file-output" class="btn btn-primary btn-icon-split" value="Excel出力">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-file-export"></i>
                                                </span>
                                                <span class="text">出力</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class=" card shadow mb-4">
                                <div class="card-header  text-gray-800" style="padding-left:2rem">
                                    移動時間表　 エクスポート
                                </div>
                                <div class="card-body">
                                    <div class="form-group col-sm-12">
                                        <div class="form-inline">
                                            <button type="submit" asp-action="ExportData" id="file-output" class="btn btn-primary btn-icon-split" value="ExportData">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-file-export"></i>
                                                </span>
                                                <span class="text">出力</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

                <form asp-controller="NonyusakiTorikomi" method="post" enctype="multipart/form-data" id="nonyusaki-upload-form" onsubmit="return false;">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card shadow mb-4">
                                <div class="card-header text-gray-800" style="padding-left:2rem">
                                    納入先情報　 インポート
                                </div>
                                <div class="card-body">
                                    <div class="form-group col-sm-12">
                                        <div class="form-inline">
                                            <div id="file-select-form" style="display:none">
                                                <input name="FileUpload" type="file" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" multiple="multiple" />
                                            </div>
                                            <button id="file-select-button" class="btn btn-light shadow mr-2">
                                                <i class="far fa-file-alt fa-fw"></i>EXCELファイル選択
                                            </button>
                                            <button type="submit" asp-action="ImportData" id="file-upload" class="btn btn-primary btn-icon-split" value=" ImportData">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-file-import"></i>
                                                </span>
                                                <span class="text">取込</span>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <p id="import-res" class="mt-1" style="font-size:13px"></p>
                                        @if (ViewData["erroremess"] != null)
                                        {
                                            <p class="text-danger float-left mt-2" id="erroremess" style="font-size:13px">@ViewData["erroremess"]</p>
                                        }
                                        @if (ViewData["successmess"] != null)
                                        {
                                            <p class="text-success float-left mt-2" id="successmess" style="font-size:13px">@ViewData["successmess"]</p>
                                        }
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row overflow-scroll">
                        <div class="col-lg-6">
                            <div class=" card shadow mb-4">
                                <div class="card-header text-gray-800" style="padding-left:2rem">
                                    エラーメッセージ
                                </div>
                                <div class="card-body" style="padding:0 0 0 20px">
                                    <div class="overflow-auto p-3 mb-3 mb-md-0 me-md-3" style=" max-height: 110px;">
                                        <div>
                                            <div>
                                                <label>エラー件数：2件</label><br>
                                                <label>1行目:可能車両入力無し</label><br>
                                                <label>2行目:可能車両入力無し</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {

            //デフォルトのファイル選択UIを非表示にして、機能だけ使用する仕掛け
            $('#file-select-button').on('click', function (e) {
                $('#file-select-form input').trigger('click');
            });

            $('#nonyusaki-upload-form').on('change', function () {
                console.log('form change!');
                HandlingFilesBeforeUpLoading();
            });

            function HandlingFilesBeforeUpLoading() {

                $('#import-res').empty;
                $('#import-res').removeClass('text-danger');

                var form = new FormData(document.querySelector("#nonyusaki-upload-form"));
                var messege = "";
                var count = 1;
                for (var file of form) {
                    console.log(file);
                    if (file[0] === "FileUpload") {
                        if (count === 1) {
                            if (file[1]["size"] <= 0) {
                                messege = ('ファイルを選択してください');
                                $('#import-res').html(messege);
                                return false;
                            }
                            else {
                                messege += count + "." + file[1]["name"];
                                $('#import-res').html(messege);
                                $("#import-res").addClass("text-info");
                                ++count;
                            }
                        }
                        else if (file[1]["size"] > 0) {
                            messege += "<br>" + count + "." + file[1]["name"];
                            $('#import-res').html(messege);
                            ++count;
                        }
                        else {
                            messege = ('不明なエラー');
                            $('#import-res').html(messege);
                            $('#import-res').addClass('text-danger');
                            return false;
                        }
                    }
                }
            }

            $('#file-upload').on('click', function (e) {

                $('#import-res').empty;
                $('#import-res').removeClass('text-danger');

                // FormData オブジェクトの利用
                var formData = new FormData(document.querySelector("#nonyusaki-upload-form"));

                var IsFirst = true;
                for (var file of formData) {
                    if (IsFirst) {
                        if (file[1]["size"] <= 0) {
                            $('#import-res').text('ファイルが選択されていません');
                            $("#import-res").addClass('text-danger');
                            //alert("ファイルを選択してください");
                            return false;
                        }
                        else {
                            IsFirst = false;
                        }
                    }

                }

                if (!confirm("インポートを行います。よろしいですか？")) {
                    return false;
                }
                else {
                    formData.append("userName", "@User.Identity.Name");

                    $.ajax({
                        url: 'Nonyusaki',
                        method: 'post',
                        data: formData,
                        processData: false,
                        contentType: false
                    }).done(function (response) {
                        if (response.res === "OK") {
                            var res = "インポート成功！！！！！！";
                            $.each(response.nameList, function (index, name) {
                                res += "\n" + (index + 1) + "." + name;
                            })
                            alert(res);
                            location.reload();
                        }
                        else {
                            $("#import-res").addClass('text-danger');
                            $("#import-res").text(response.error);
                            form.reset();

                        }
                    }).fail(function (jqXHR, textStatus, errorThrown) {
                        console.log("jqXHR", jqXHR);
                        console.log("textStatus", textStatus);
                        console.log("errorThrown", errorThrown);
                        $("#import-res").addClass('text-danger');
                        $("#import-res").text("サーバーとの通信に失敗しました");
                    });
                }
            });
        });
    </script>
}