source/RouteOptiWeb/Controllers/NonyusakiIchiranController.cs
using Microsoft.AspNetCore.Mvc;
using RouteOptiWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using X.PagedList;


namespace RouteOptiWeb.Controllers
{
    public class NonyusakiIchiranController : Controller
    {
        public IActionResult Index(NonyusakiTourokuModel model)
        {
            if (model == null)
            {
                model = new NonyusakiTourokuModel();
            }
            var list = GetIchiran(model.NonyusakiSearch);
            if (list.Count > 0)
            {
                IEnumerable<NonyusakiTourokuModel> query = list.Select(s => s);
                model.NonyusakiList = query.ToPagedList();
            }
            return View(model);

        }

        //[HttpPost]--初めて納入先一覧画面表示する================================
        private List<NonyusakiTourokuModel> GetIchiran(string NonyusakiSearch)
        {
            DataTable dt;
            List<NonyusakiTourokuModel> strList = new List<NonyusakiTourokuModel>();

            using (MSSQLAccess database = new MSSQLAccess())
            {
                //パラメーターをクリアー
                database.ClearParam();

                string sqlstr = @$" SELECT * FROM [m_into] AS A
                                    LEFT OUTER JOIN [m_address] AS B
        		                    ON A.address_no = B.address_no
                                    LEFT OUTER JOIN [m_area] AS C
        		                    ON A.area_no = C.area_no 
                                    WHERE (1=1)";

                if (!string.IsNullOrEmpty(NonyusakiSearch))
                {
                    NonyusakiSearch = NonyusakiSearch.Trim();
                    database.SetParam("@value", SqlDbType.NVarChar, NonyusakiSearch);//Search値         

                    if (NonyusakiSearch == "有")
                    {
                        sqlstr += @$"AND (time_flg LIKE  (''+1+''))";

                    }
                    else if (NonyusakiSearch == "無")
                    {
                        sqlstr += @$"AND (time_flg LIKE  (''+0+''))";
                    }
                    else if (NonyusakiSearch == "○")
                    {
                        sqlstr += @$"AND (week LIKE ('%'+ '1' +'%')
                                   OR depo_flg LIKE (''+1+'')
                                   )";
                    }
                    else
                    {
                        sqlstr += @$"AND (into_cd LIKE  ('%'+@value+'%')
                                   OR into_name LIKE  ('%'+@value+'%')
                                   OR address LIKE  ('%'+@value+'%')
                                   OR bin_no LIKE  ('%'+@value+'%')
                                   OR area_name LIKE  ('%'+@value+'%')
                                   OR available_car LIKE  ('%'+@value+'%')
                                   OR start_time LIKE  ('%'+@value+'%')
                                   OR end_time LIKE  ('%'+@value+'%')
                                   OR work_time LIKE  ('%'+@value+'%')
                                   )";
                    }
                }
                //最後に並べ替えを行う
                //sqlstr += "ORDER BY into_cd";

                dt = database.SelectData(sqlstr);

                NonyusakiTourokuModel Nonyusaki;
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    Nonyusaki = new NonyusakiTourokuModel();
                    Nonyusaki.Into_Cd = dt.Rows[i]["into_cd"].ToString();
                    Nonyusaki.Into_Name = dt.Rows[i]["into_name"].ToString();
                    Nonyusaki.Address = dt.Rows[i]["address"].ToString();
                    Nonyusaki.Bin_No = dt.Rows[i]["bin_no"].ToString();
                    Nonyusaki.Available_car = dt.Rows[i]["available_car"].ToString();
                    if (dt.Rows[i]["time_flg"] != System.DBNull.Value)
                        Nonyusaki.Time_FLG = Convert.ToBoolean(dt.Rows[i]["time_flg"]);
                    Nonyusaki.Start_Time = dt.Rows[i]["start_time"].ToString();
                    Nonyusaki.End_Time = dt.Rows[i]["end_time"].ToString();
                    Nonyusaki.Work_time = dt.Rows[i]["work_time"].ToString();
                    Nonyusaki.Week = dt.Rows[i]["week"].ToString();
                    if (dt.Rows[i]["area_no"] != System.DBNull.Value && (int)dt.Rows[i]["area_no"] != 0)
                    {
                        Nonyusaki.Area_No = (int)dt.Rows[i]["area_no"];
                        database.SetParam("@Area_No", SqlDbType.Int, Nonyusaki.Area_No);//エリア
                        //[m_area]Tableでは(area_no)値を見ます===================================
                        string sql_areaname = $@"SELECT (area_name) AS area_name
                                       FROM [m_area]
                                       WHERE (1 = 1) 
                                       AND(area_no = @Area_No) ";
                        var select_area = database.SelectData(sql_areaname);
                        Nonyusaki.Area_Name = select_area.Rows[0]["area_name"].ToString();
                    }
                    Nonyusaki.Depo_FLG = Convert.ToBoolean(dt.Rows[i]["depo_flg"]);
                    strList.Add(Nonyusaki);
                }
                return strList;
            }
        }
        //========================================================================

        /////////POST:/Edit.--初めて納入先修正の画面表示する===========================
        public ActionResult Edit(string cd, string bin, string week)
        {
            try
            {
                List<NonyusakiTourokuModel> list = GetNonyusaki(cd, bin, week);
                return View(list.FirstOrDefault());
            }
            catch (Exception ex)
            {
                ViewData["Error"] = "データベース登録処理エラー";
                return RedirectToAction("Index");
            }
        }

        /////////Get: チェック値////Button.
        public ActionResult StylesButton(string editButton, string deleteButton, NonyusakiTourokuModel value)
        {
            if (editButton != null)
            {
                return EditUpdate(value);
            }
            else if (deleteButton != null)
            {
                return deleteData(value);
            }
            else
            {
                return View();
            }
        }

        //[HttpPost]-------------------------------------
        private List<NonyusakiTourokuModel> GetNonyusaki(string cd, string bin, string week)
        {
            DataTable dt;
            List<NonyusakiTourokuModel> strEditList = new List<NonyusakiTourokuModel>();
            using (MSSQLAccess database = new MSSQLAccess())
            {
                //パラメーターをクリアー
                database.ClearParam();
                //パラメータ必須-------------------------------------------------------------
                database.SetParam("@cd", SqlDbType.NVarChar, cd); //納入先コード
                database.SetParam("@bin", SqlDbType.NVarChar, bin); //便No
                database.SetParam("@week", SqlDbType.NVarChar, week);//曜日指定
                //---------------------------------------------------------------------------

                string sqlstr = @$" SELECT * FROM [m_into] AS A
                                    LEFT OUTER JOIN [m_address] AS B
        		                    ON A.address_no = B.address_no    
                                    LEFT OUTER JOIN [m_area] AS C
        		                    ON A.area_no = C.area_no
                                    WHERE (A.into_cd  = @cd)
                                      AND (A.bin_no   = @bin)
                                      AND (A.week     = @week) ";

                dt = database.SelectData(sqlstr);
                NonyusakiTourokuModel strEdit;
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    strEdit = new NonyusakiTourokuModel();
                    strEdit.Into_Cd = dt.Rows[i]["into_cd"].ToString();
                    strEdit.Into_Name = dt.Rows[i]["into_name"].ToString();
                    strEdit.Address = dt.Rows[i]["address"].ToString();
                    strEdit.Bin_No = dt.Rows[i]["bin_no"].ToString();
                    strEdit.Available_car = dt.Rows[i]["available_car"].ToString();
                    if (dt.Rows[i]["time_flg"] != System.DBNull.Value)
                        strEdit.Time_FLG = Convert.ToBoolean(dt.Rows[i]["time_flg"]);
                    strEdit.Start_Time = dt.Rows[i]["start_time"].ToString();
                    strEdit.End_Time = dt.Rows[i]["end_time"].ToString();
                    strEdit.Work_time = dt.Rows[i]["work_time"].ToString();
                    strEdit.Week = dt.Rows[i]["week"].ToString();
                    if (dt.Rows[i]["area_no"] != System.DBNull.Value)
                        strEdit.Area_No = (int)dt.Rows[i]["area_no"];
                    strEdit.Area_Name = dt.Rows[i]["area_name"].ToString();
                    strEdit.Depo_FLG = Convert.ToBoolean(dt.Rows[i]["depo_flg"]);
                    strEditList.Add(strEdit);
                }
                return strEditList;
            }
        }
        //==============================================================================

        ////// EDIT:Update納入先更新/======================================================
        [HttpPost]
        private ActionResult EditUpdate(NonyusakiTourokuModel Nonyusaki)
        {
            using (MSSQLAccess database = new MSSQLAccess())
            {
                int depo_flg = 0;
                int time_flg = 0;

                depo_flg = (Nonyusaki.Depo_FLG == true) ? 1 : 0;
                time_flg = (Nonyusaki.Time_FLG == true) ? 1 : 0;

                //曜日全てチェックなしならエラーにする
                if (Nonyusaki.Week == "0000000")
                {
                    ViewData["Error"] = "いづれかの曜日をチェックしてください。";

source/RouteOptiWeb/Views/NonyusakiIchiran/Edit.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model RouteOptiWeb.Models.NonyusakiTourokuModel

@{
    ViewData["Title"] = "納入先情報修正画面";
    Layout = "_Layout";
}

<div class="h4 mb-3 text-gray-800">
    @ViewData["Title"]
</div>

<div class="card shadow mb-4 c-dialog">
    <div class="card-header text-gray-800">
        納入先情報修正画面
    </div>
    <div class="card-body">
        <form class="col-md-12" method="post" asp-controller="NonyusakiIchiran" asp-action="StylesButton">
            <div class="btn-header">
                <div class="btn-headerRight">
                    <button type="button" onclick="goBack()" class="btn btn-light">
                        <i class="fas fa-arrow-alt-circle-left"></i>
                        戻る
                    </button>
                </div>
            </div>

            <div class="valid-area">
                <span id="FailMsg" class="text-danger">@ViewData["Error"] </span>
                <span id="SuccessMsg" class="text-success">@ViewData["Message"]</span>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label class="c-label-text">納入先名 </label>
                </div>
                <div class="col-md-5">
                    <input type="text" asp-for="Into_Name" class="form-control">
                    <span asp-validation-for="Into_Name" class="text-danger"></span>
                </div>
                <div class="col-md-2">
                    <label class="c-label-text text-right">納入先コード</label>
                </div>
                <div class="col-md-3">
                    <input type="text" asp-for="Into_Cd" class="form-control" readonly>
                    @Html.HiddenFor(Model => Model.Into_Cd)
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label class="c-label-text">住所</label>
                </div>
                <div class="col-md-10">
                    <input type="text" asp-for="Address" class="form-control">
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2" id="bin_text">
                    <label class="control-label c-label-text">便No</label>
                </div>
                <div class="col-md-1" id="bin_number">
                    <input type="number" asp-for="Bin_No" class="form-control" readonly>
                    @Html.HiddenFor(Model => Model.Bin_No)
                </div>
                <div class="col-md-2" id="Available_text">
                    <label class="c-label-text text-right">可能車両</label>
                </div>
                <div class="col-md-2" id="Available_select">
                    <select asp-for="Available_car" onchange="this.nextElementSibling.value=this.value" class="form-control">
                        <option value="8tまで"> 8tまで</option>
                        <option value="12t（8694以外）まで"> 12t（8694以外）まで</option>
                        <option value="12tまで"> 12tまで</option>
                        <option value="15tだけﾀﾞﾒ"> 15tだけﾀﾞﾒ</option>
                        <option value="15tまで"> 15tまで</option>
                        <option value="全てOK（トレーラ含む）"> 全てOK（トレーラ含む）</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="control-label c-label-text text-right">納入先作業時間(分)</label>
                </div>
                <div class="col-md-2">
                    <input type="number" asp-for="Work_time" class="form-control" placeholder="" id="time_number">
                    <span asp-validation-for="Work_time" class="text-danger"></span>
                </div>
            </div>

            <div class="row" id="radio_div">
                <div class="col-md-2">
                    <label class="c-label-text">時間指定</label>
                </div>
                <input type="text" style="display:none" asp-for="Time_FLG" id="box_radio">
                <div class="col-md-1">
                    <input class="form-check-input" type="radio" name="Time_FLG" id="radio1" value=""> 有
                </div>

                <div class="col-md-1">
                    <input class="form-check-input" type="radio" name="Time_FLG" id="radio2" value=""> 無
                </div>
            </div>

            <div class="row" id="Time_div">
                <div class="col-md-2"></div>
                <div class="col-md-2">
                    <label class="c-label-text text-right">時間指定開始</label>
                </div>
                <div class="col-md-1.5">
                    <input class="form-control" id="appt-time1" type="time" name="Start_Time" asp-for="Start_Time">
                    <span asp-validation-for="Start_Time" class="text-danger"></span>
                </div>
                <div class="col-md-2">
                    <label class="c-label-text text-right">時間指定終了</label>
                </div>
                <div class="col-md-1.5">
                    <input class="form-control" id="appt-time2" type="time" name="End_Time" asp-for="End_Time">
                    <span asp-validation-for="End_Time" class="text-danger"></span>
                </div>
            </div>

            <input style="display:none" asp-for="Week" />
            <input style="display:none" asp-for="Week_DB" />
            <div class="row" id="checkbox_div">
                <div class="col-md-2">
                    <label class="c-label-text">曜日指定</label>
                </div>
                <input type="text" asp-for="Week" id="checkbox" hidden>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox1" checked /> 月
                </div>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox2" checked /> 火
                </div>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox3" checked /> 水
                </div>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox4" checked /> 木
                </div>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox5" checked /> 金
                </div>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox6" checked /> 土
                </div>
                <div class="col-md-1">
                    <input type="checkbox" id="checkbox7" checked /> 日
                </div>
            </div>

            <div class="row">
                <div class="col-md-2" id="area_text">
                    <label class="c-label-text">エリア</label>
                </div>
                <div class="col-md-2" id="area_select">
                    <select asp-for="Area_Name" onchange="this.nextElementSibling.value=this.value" class="form-control">
                        <option value="西三河"> 西三河</option>
                        <option value="東三河"> 東三河</option>
                        <option value="静岡"> 静岡</option>
                        <option value="三重"> 三重</option>
                        <option value="長野"> 長野</option>
                        <option value="知多"> 知多</option>
                    </select>
                </div>
                <div class="col-md-2"></div>

                <div class="col-md-2">
                    <input type="checkbox" id="check_depo" asp-for="Depo_FLG" disabled /> デポ
                    <input type="text" asp-for="Depo_FLG" hidden />
                </div>
            </div>
            <div class="row">
                <div class="c-dialog-area col-md-2" style="padding-left:0px">
                    <button type="submit" id="NonyuEdit" name="editButton" value="保存" class="btn btn-success btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-check"></i>
                        </span>
                        <span class="text">保存</span>
                    </button>
                </div>
                <div class="col-md-8"></div>
                <div class="c-dialog-area col-md-2" style="padding-right:0px">
                    <button type="submit" id="NonyuDelete" name="deleteButton" value="削除" class="btn btn-danger btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-trash"></i>
                        </span>
                        <span class="text">削除</span>
                    </button>
                </div>

            </div>


        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(function () {
            $("#radio1").on('change', function () {
                if ($("#radio1").prop("checked") == true) {
                    $("#box_radio").val('True');
                    $("#appt-time1").prop('readonly', false);
                    $("#appt-time2").prop('readonly', false);
                }
                else {
                    $("#box_radio").val('False');
                    $("#appt-time1").prop('readonly', true);
                    $("#appt-time2").prop('readonly', true);
                }
            })
            //=================================================
            $("#radio2").prop("checked", true);
            if ($("#radio2").prop("checked", true)) {
                $("#appt-time1").prop('readonly', true);
                $("#appt-time2").prop('readonly', true);
            }
            if (($("#box_radio").val() == 'True')) {
                $("#radio1").prop("checked", true);
                $("#appt-time1").prop('readonly', false);
                $("#appt-time2").prop('readonly', false);
            } else {
                $("#radio2").prop("checked", true);
            }
            //================

            //============================================================
            for (let i = 0; i < $("#checkbox").val().length; i++) {
                let j = i + 1;
                var week = "#checkbox" + j;
                if ($("#checkbox").val()[i] == '1') {
                    $(week).prop('checked', true);
                } else {
                    $(week).prop('checked', false);
                }
            }

            ////チェックWeekの値を初期状態で送信する================================
            var arrcheck = $("#checkbox1").closest(".row").find("input[type='checkbox']");
            var week = "";
            for (var item of arrcheck) {
                if (item.checked == true) {
                    week += "1";
                }
                else {
                    week += "0";
                }
            }
            $("#Week_DB").val(week);

            ///Depoチェックを実施する。
            //======================================================
            if ($("#check_depo").prop("checked") == true) {
                $("#bin_text").css("visibility", "hidden");
                $("#bin_number").css("visibility", "hidden");
                $("#Available_text").css("visibility", "hidden");
                $("#Available_select").css("visibility", "hidden");
                $("#radio_div").css("visibility", "hidden");
                $("#Time_div").css("visibility", "hidden");
                $("#checkbox_div").css("visibility", "hidden");
                $("#area_text").css("visibility", "hidden");
                $("#area_select").css("visibility", "hidden");
                ($("#check_depo_return").val() == 'True')
            }
            ///=============================================================
            $('#NonyuEdit').on('click', function () {
                if (($("#radio1").prop("checked") == true) && ($("#check_depo").prop("checked") == false)) {
                    if (convertTime($("#appt-time1").val()) >= convertTime($("#appt-time2").val())) {
                        alert("時間指定終了が先になっています。");
                        return false;
                    }
                }

                //チェックWeekの値を初期状態で送信する================================
                var arrcheck = $("#checkbox1").closest(".row").find("input[type='checkbox']");
                var week = "";
                for (var item of arrcheck) {
                    if (item.checked == true) {
                        week += "1";
                    }
                    else {
                        week += "0";
                    }
                }
                $("#Week").val(week);
                //============================================================

                if (!confirm('修正することを保存します。よろしいですか？')) {
                    return false;
                } else {
                    $(this).submit();
                }
            });
            function convertTime(Time) {
                var Data = Time.split(":");
                let a = Data[0] * 60 + Data[1];
                return parseInt(a);
            }
            //============================================================
            $('#NonyuDelete').on('click', function () {
                if (!confirm('削除を保存します。よろしいですか？')) {
                    return false;
                } else {
                    $(this).submit();
                }
            });
            //============================================================
        });
        function goBack() {
            var urlTop =
                $(location).attr('protocol') + '//' + $(location).attr('host') + '/';
            window.location = urlTop + "nonyusakiichiran";
        }
            //============================================================
    </script>
}

source/RouteOptiWeb/Views/NonyusakiIchiran/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model RouteOptiWeb.Models.NonyusakiTourokuModel

@{
    ViewData["Title"] = "納入先情報一覧画面";
    Layout = "_Layout";
}

<div class="h4 mb-3 text-gray-800">
    @ViewData["Title"]
</div>

<div class="card shadow mb-4">
    <div class="card-header text-gray-800">
        納入先情報 一覧画面
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12 d-flex flex-row bd-highlight">
                <form class="form-inline ml-3" method="post" asp-controller="NonyusakiIchiran" asp-action="Index">
                    <input type="text" asp-for="NonyusakiSearch" id="tbxProductSearch" class="form-control col-9 mr-1" placeholder="キーワード" />
                    <button type="submit" class="btn btn-light btn-square" title="検索">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordered table-white table-sm">
                    <thead class="thead-light text-center">
                        <tr class="form-group">
                            <th class="align-middle table-bordered"></th>
                            <th class="align-middle table-bordered">納入先<br>コード</th>
                            <th style="min-width: 150px" class="align-middle table-bordered">納入先名</th>
                            <th style="min-width: 250px" class="align-middle table-bordered">住所</th>
                            <th class="align-middle table-bordered">便No</th>
                            <th style="min-width: 100px" class="align-middle table-bordered">可能車両</th>
                            <th class="align-middle table-bordered">納入先<br>作業時間<br>[分]</th>
                            <th class="align-middle table-bordered">時間<br>指定</th>
                            <th class="align-middle table-bordered">時間<br>指定<br>開始</th>
                            <th class="align-middle table-bordered">時間<br>指定<br>終了</th>
                            <th class="align-middle table-bordered">月</th>
                            <th class="align-middle table-bordered">火</th>
                            <th class="align-middle table-bordered">水</th>
                            <th class="align-middle table-bordered">木</th>
                            <th class="align-middle table-bordered">金</th>
                            <th class="align-middle table-bordered">土</th>
                            <th class="align-middle table-bordered">日</th>
                            <th class="align-middle table-bordered">エリア</th>
                            <th class="align-middle table-bordered">デポ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.NonyusakiList != null)
                        {
                            @foreach (var obj in @Model.NonyusakiList)
                            {
                                <tr>
                                    <td class="text-center">
                                        <button type="button" class="btn btn-light btn-square" onclick="location.href='@Url.Action("Edit", "NonyusakiIchiran", new { cd = obj.Into_Cd, bin = obj.Bin_No,week = obj.Week} )'; return false;" title="修正">
                                            <i class="fas fa-edit"></i>
                                        </button>
                                    </td>
                                    <td class="text-center">@obj.Into_Cd</td>
                                    <td class="text-center">@obj.Into_Name</td>
                                    <td class="text-center">@obj.Address</td>
                                    <td class="text-center">@obj.Bin_No</td>
                                    <td class="text-center">@obj.Available_car</td>
                                    <td class="text-center">@obj.Work_time</td>
                                    @if (@obj.Time_FLG == true)
                                    {
                                        <td class="text-center">有</td>
}
                                    else
                                    {
                                        <td class="text-center">無</td>
}
                                    <td class="text-center">@obj.Start_Time</td>
                                    <td class="text-center">@obj.End_Time</td>
                                    @for (int i = 0; i < obj.Week.Length; i++)
                                    {
                                        if (@obj.Week[i] == '1')
                                        {
                                            <td class="text-center">○</td>
}
                                        else
                                        {
                                            <td class="text-center"></td>
}
                                    }
                                    <td class="text-center">@obj.Area_Name</td>
                                    @if (@obj.Depo_FLG == true)
                                    {
                                        <td class="text-center">○</td>
}
                                    else
                                    {
                                        <td class="text-center"></td>
}
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>