source/RouteOptiWeb/Controllers/KanouSyaryouController.cs
using Microsoft.AspNetCore.Mvc;
using RouteOptiWeb.Common;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RouteOptiWeb.Controllers
{
    public class KanouSyaryouController : Controller
    {
        private readonly string ErrorMsg = "接続異常のためネットワーク接続を確認してください。";
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ExcelButton()
        {
            DataTable dt = GetAvailableCarData();

            //会社ID取得
            int wid = int.Parse(User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).First().Value);
            //ユーザー名取得
            string userCode = User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).Skip(2).First().Value.ToString();

            // ファイル名
            var tmpFilename = "可能車両車格取込_" + wid + "_" + userCode + DateTime.Now.ToString("yyyyMMddHHmmss");

            // 出力フォルダパス
            var rootPath = Directory.GetCurrentDirectory();
            var folderPath = Path.Combine(rootPath, @"wwwroot\DownloadFiles\Kanousyaryou");

            //Webサーバーのダウンロードのフォルダーが存在しないる場合に新規作成
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            // 出力パス
            var expPath = Path.Combine(folderPath, tmpFilename);

            //ヘッダーのリストを作成
            List<string> hederList = new List<string>();
            hederList.Add("可能車両");
            hederList.Add("車格");
            hederList.Add("割付係数");

            // Excelファイル生成
            bool exportRs = Util.ExportExcel(dt, expPath, hederList, null, "", "可能車両車格取込");
            if (exportRs)
            {
                var file = System.IO.File.ReadAllBytes(expPath);
                return File(file, System.Net.Mime.MediaTypeNames.Application.Octet, "可能車両車格取込.xlsx");
            }
            else
            {
                ViewData["Error"] = ErrorMsg;
                return View("Index");
            }
        }

        private DataTable GetAvailableCarData()
        {
            DataTable data;
            using (MSSQLAccess database = new MSSQLAccess())
            {
                //パラメーターをクリアー
                database.ClearParam();

                //---------------------------------------------------------------------------
                string sqlstr = @$" SELECT * FROM  [m_available_car] ";
                data = database.SelectData(sqlstr);
            }
            return data;
        }
    }
}

source/RouteOptiWeb/Views/KanouSyaryou/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core

@{
    ViewData["Title"] = "可能車両車格取込画面";
    Layout = "_Layout";
}
<style>
    .row {
        margin-right: 0rem;
        margin-left: 0rem;
    }
    label {
        position: relative;
        z-index: 0;
        display: inline-block;
    }
    label:hover {
        color: #fff;
    }
    label::before {
        z-index: -1;
        position: absolute;       
        content: '';
        display: block;
        width: 100%;
        height: 100%;
        background: #0a516d;
        transform: scaleX(0);
        transform-origin: right;
    }
    label:hover::before {
        transform: scaleX(1);
        transform-origin: left;
    }
</style>

<div class="row">
    <div style="width:800px">
        <div class="h4 mb-3 text-gray-800">
            @ViewData["Title"]
        </div>
        <div class="card shadow mb-4">
            <div class="card-header text-gray-800">
                可能車両車格取込画面
            </div>
            <div class="card-body">
                <div class="valid-area">
                    <span id="FailMsg" class="text-danger">@ViewData["Error"] </span>
                </div>
                <form asp-controller="KanouSyaryou" method="post" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class=" card shadow mb-4">
                                <div class="card-header text-gray-800" style="padding-left:2rem">
                                    エクスポート
                                </div>
                                <div class="card-body">
                                    <div class="form-group col-sm-12">
                                        <div class="form-inline">
                                            <button type="submit" asp-action="ExcelButton" id="file-output" class="btn btn-primary btn-icon-split" value="Excel出力">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-file-export"></i>
                                                </span>
                                                <span class="text">出力</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

                <form asp-controller="KanouSyaryou" method="post" enctype="multipart/form-data" id="nonyusaki-upload-form" onsubmit="return false;">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card shadow mb-4">
                                <div class="card-header text-gray-800" style="padding-left:2rem">
                                    インポート
                                </div>
                                <div class="card-body">
                                    <div class="form-group col-sm-12">
                                        <div class="form-inline">
                                            <div id="file-select-form" style="display:none">
                                                <input name="FileUpload" type="file" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" multiple="multiple" />
                                            </div>
                                            <button id="file-select-button" class="btn btn-light shadow mr-2">
                                                <i class="far fa-file-alt fa-fw"></i>EXCELファイル選択
                                            </button>
                                            <button type="submit" asp-action="ImportData" id="file-upload" class="btn btn-primary btn-icon-split" value=" ImportData">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-file-import"></i>
                                                </span>
                                                <span class="text">取込</span>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <p id="import-res" class="mt-1" style="font-size:13px"></p>
                                        @if (ViewData["errorMsg"] != null)
                                        {
                                            <p class="text-danger float-left mt-2" id="erroremess" style="font-size:13px">@ViewData["errorMsg"]</p>
                                        }
                                        @if (ViewData["successMsg"] != null)
                                        {
                                            <p class="text-success float-left mt-2" id="successmess" style="font-size:13px">@ViewData["successMsg"]</p>
                                        }
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row overflow-scroll">
                        <div class="col-lg-6 card shadow mb-4" style="padding: 0rem">
                            <div class="card-header text-gray-800" style="padding-left:2rem">
                                エラーメッセージ
                            </div>
                            <div class="card-body" style="padding:0 0 0 20px">
                                <div class="overflow-auto p-3 mb-3 mb-md-0 me-md-3" style=" max-height: 110px;">
                                    <label></label><br>
                                    <label></label><br>
                                    <label></label><br>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>