source/RouteOptiWeb/Controllers/PlanController.cs
using Microsoft.AspNetCore.Mvc;
using RouteOptiWeb.Models;
using RouteOptiWeb.Common;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Security.Claims;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using X.PagedList;
using Microsoft.AspNetCore.Http;
using System.Net.Mail;
using System.Net;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;

namespace RouteOptiWeb.Controllers
{
    public class PlanController : Controller
    {
        private int iSeqId = 0;

        [HttpGet, HttpPost]
        public IActionResult Index(PlanModel model)
        {
            if (model == null)
            {
                model = new PlanModel();
            }
            iSeqId += 1;
            model.STATUS = Consts.C_JSON_OK;
            model.MESSAGE = string.Empty;
            model.SEQID = (iSeqId).ToString();
            model.PROGRESS = string.Empty;

            return View("Index", model);
        }

        [HttpGet, HttpPost]
        public IActionResult ResultOK(PlanModel model)
        {
            if (model == null)
            {
                model = new PlanModel();
            }

            model.STATUS = Consts.C_JSON_NG;
            return View("Result", model);
        }

        [HttpGet, HttpPost]
        public IActionResult ResultNG(PlanModel model)
        {
            if (model == null)
            {
                model = new PlanModel();
            }

            model.STATUS = Consts.C_JSON_NG;
            //model.ERR_MESSAGE = myString;
            return View("Result", model);
        }

        [HttpGet, HttpPost]
        public IActionResult DspList(PlanModel model)
        {
            if (model == null)
            {
                model = new PlanModel();
            }

            return View("DspList", model);
        }


        [HttpPost]
        public JsonResult GetProgress([FromBody] Dictionary<string, string> LstRecive)
        {
            ProgressModel progressModel = ProgressModel.GetInstance();
            string strSeqId = null;

            if (LstRecive.Count > 0) 
            {
                strSeqId = LstRecive[Consts.C_JSON_SEQID];
            }
            if (null == strSeqId || null == progressModel)
            {
                List<Dictionary<string, string>> parNG = new List<Dictionary<string, string>>();
                parNG.Add(new Dictionary<string, string>() { { Consts.C_JSON_STATUS, Consts.C_JSON_NG } });
                parNG.Add(new Dictionary<string, string>() { { Consts.C_JSON_MESSAGE, Consts.C_JSON_NG_CONTINUE } });
                parNG.Add(new Dictionary<string, string>() { { Consts.C_JSON_PROGRESS, "0" } });
                string jsonNG = JsonSerializer.Serialize(parNG);
                return Json(jsonNG);
            }


            List<Dictionary<string, string>> par = new List<Dictionary<string, string>>();
            par.Add(new Dictionary<string, string>() { { Consts.C_JSON_STATUS, progressModel.getStatus(strSeqId) } });
            par.Add(new Dictionary<string, string>() { { Consts.C_JSON_MESSAGE, progressModel.getMessage(strSeqId) } });
            par.Add(new Dictionary<string, string>() { { Consts.C_JSON_PROGRESS, progressModel.getProgress(strSeqId) } });
            string strJson = JsonSerializer.Serialize(par);

            return Json(strJson);
        }

        //計画作成
        public ActionResult Create(string strSeqId)
        {
            try
            {
                Dictionary<string, string> LstRecive = new Dictionary<string, string>();
                LstRecive.Add(Consts.C_JSON_SEQID, strSeqId);
                LstRecive.Add(Consts.C_JSON_STATUS, Consts.C_JSON_OK);
                LstRecive.Add(Consts.C_JSON_MESSAGE, "");
                LstRecive.Add(Consts.C_JSON_PROGRESS, "0");

                ProgressModel.GetInstance().setData(strSeqId, LstRecive);

                string myPythonApp = @"wwwroot\python\CVRP.py";
                //string myPythonApp = @"wwwroot\python\RouteOptiSample.py";
                Process myProcess = new Process()
                {
                    StartInfo = new ProcessStartInfo(@"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe")
                    {
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        Arguments = myPythonApp + " " + strSeqId
                    }
                };

                myProcess.Start();
                StreamReader myStreamReader = myProcess.StandardOutput;
                string myString = myStreamReader.ReadLine();
                myProcess.WaitForExit();
                myProcess.Close();

                Console.WriteLine("Value received from script: " + myString);

                if (myString.Equals(Consts.C_PYTHON_COMPLETE))
                {
                    return RedirectToAction("ResultOK");
                }
                else
                {
                    return RedirectToAction("ResultNG");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return RedirectToAction("ResultNG");
            }
        }

        public ActionResult DspList()
        {
            return RedirectToAction("DspList");
        }
    }
}

source/RouteOptiWeb/Views/Plan/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model RouteOptiWeb.Models.PlanModel
@{
    ViewData["Title"] = "配送計画自動作成画面";
    Layout = "_Layout";
}

<SignalR.EMPLOYEE>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>  

<div class="h4 mb-3 text-gray-800">
    @ViewData["Title"]
</div>
<div class="card shadow mb-4">

    <div class="card-body">
        <div>作成速度</div><div id="outputSlider"></div>
        <input id="slider1" type="range" value="8" min="1" max="10" />

        <div class="row">
            <div class="col-md-12 d-flex flex-row bd-highlight">
                <button type="button" class="btn btn-light btn-circle" onclick="location.href='@Url.Action("Create", "Plan", new { strSeqId = Model.SEQID } )'; return false;" title="立案" id="btnPlan">
                    <i class="fas fa-plus"></i>
                </button>
            </div>
        </div>
        <div class="progress">
            <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" id="lblStatus">
            </div>
        </div>
        <div id="lblProgress"></div>
    </div>
</div>

<!--親jsファイル呼び出し-->
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script type="text/javascript">
        $(function () {

            $("#btnPlan").on("click", function (e) {
                var state = document.getElementById("lblProgress");
                state.innerHTML = "作成開始...";

            });
            $("#btnPlan").on("click", function (e) {
                var sendJson = { SEQID: String(@Model.SEQID) };
                console.log("開始しました！sendJson:" + sendJson);
                var intervalId  = setInterval(function () {
                    $.ajax({

                        type: "POST",
                        url: "../plan/GetProgress",
                        data: JSON.stringify(sendJson),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        async: false,
                        success: function (result) {
                            var retJson = JSON.parse(result);

                            if ("OK" == retJson[0].STATUS) {
                                updateProgress(retJson[2].PROGRESS, 100);
                            }
                            else
                            {
                                clearInterval(intervalId);
                                $("#lblProgress").text(retJson[1].MESSAGE);
                                return false;
                            }
                        },
                        error: function (errormessage) {
                            clearInterval(intervalId);
                            $("#lblProgress").text(errormessage.responseText);
                            return false;
                        }
                    });
                    var state = document.getElementById("lblProgress");
                    //console.log("result" + state.innerHTML);
                    if ("完了"==state.innerHTML) {
                        clearInterval(intervalId);
                        console.log("停止しました！");
                    }
                }, 5000);

                function updateProgress(count, max) {
                    var state = document.getElementById("lblProgress");
                    if (count <= max) {
                        count1 = parseInt(count / (max / 100));
                        $('#lblProgress').text('進捗' + count1 + '% 完了');
                        var lblStatus = document.getElementById("lblStatus");
                        lblStatus.style.width = count1 + "%";
                        $("#lblStatus").text(count1 + '% Complete');
                    }
                    if (count >= max) {
                        $('#lblProgress').text('完了');
                    }
                }
            });

            $(window).onload =(function () {
                var slider = document.getElementById("slider1");
                slider.addEventListener('scroll', () => {
                    var slider = document.getElementById("slider1");
                    var out_frame = document.getElementById("outputSlider");
                    out_frame.innerText = slider.value;
                });
            });
        });
</script>
}

source/RouteOptiWeb/Views/Plan/Result.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model RouteOptiWeb.Models.PlanModel
@{
    ViewData["Title"] = "配送計画自動作成結果表示画面";
    Layout = "_Layout";
}

<div class="h4 mb-3 text-gray-800">
    @ViewData["Title"]
</div>
<div class="card shadow mb-4">

    <div class="card-body">
        <div>自動作成成功</div>
        <div>割付済件数○○件</div>
        <div>未割付件数○○件</div>
        <a href="~/html/map.html" class="btn btn-secondary" target="_blank">配送経路地図表示</a>
        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("DspList", "Plan" )'; return false;" title="新規作成" id="btnPlan">配送計画一覧表示</button>
        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Plan" )'; return false;" title="新規作成" id="btnPlan">戻る</button>
    </div>
</div>